Workflow and pre-commit added
ansible-lockdown/RHEL9-CIS pull request #81
Opened 2023-08-02 15:49 UTC by uk-bolly

**Overall Review of Changes:**

- new workflow configuration
  - Allowing devel and main configs
  - IaC code found in alternate repo for easier mgmt
  - separate pipeline configs
  - new pre-commit testing
  - linting tested
- Added pre-commit config - Does not have to be used but can improve things
  - .pre-commit-config.yaml
  - .config/.secrets.baseline

- updated to logic in 5.6.5
- lint updates to 6.1.x
- readme updates
- audit control updates and variable name changes
  - ability to run audit on arm64(e.g. pi or M1/2) too thanks to @lucab85 #77
- tidy up README adopted PR #78 thanks to @lucab85
- moved Makefile requirements.txt to .config/
- removed .ansible.cfg and local.yml
- README button updates

**How has this been tested?:**
seperate pipe and repo
manuall

2023-08-02 15:54 UTC, uk-bolly commented
expect pre-commit to fail as not yet in the commited repo and
expect current pipeline to fail and files no longer exist in repo

2023-08-03 12:59 UTC, MrSteve81 commented on README.md
I know it minor but to keep the readme looking pretty your github tag needs to be done like this for the pieplines. 
[![Main Pipeline Status]
[![Devel Pipeline Status]

2023-08-03 13:07 UTC, MrSteve81 requested changes
I know its minor but to keep the readme looking pretty your github tag needs to be done like this for the pieplines.
[![Main Pipeline Status]
[![Devel Pipeline Status]

2023-08-08 12:59 UTC, georgenalen approved these changes
Looks good!

2023-08-08 13:18 UTC, merged